import { sql } from './db.js'

//tipo usuário
sql`
    CREATE TABLE "tipoUsuario" (
    "id_tipousuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL
    );
`
.then(() => {
    sql`
    CREATE TABLE "usuario" (
        "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "email" VARCHAR(255) UNIQUE NOT NULL,
        "password" VARCHAR(255) NOT NULL,
        "firstName" VARCHAR(100) NOT NULL,
        "lastName" VARCHAR(100) NOT NULL,
        "id_tipousuario" INTEGER REFERENCES "tipoUsuario"("id_tipousuario"),
        "isNutritionist" BOOLEAN DEFAULT false,
        "crn" VARCHAR(255),
        "photoUrl" TEXT,
        "phone" VARCHAR(20)
    );
`
    .then(() => {
        sql`
    CREATE TABLE "recipes" (
    "id_recipe" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "image" varchar(255) NOT NULL,
    "description" text NOT NULL,
    "steps" text NOT NULL,
    "calories" integer NOT NULL,
    "prepTime" integer NOT NULL,
    "id_usuario" integer NOT NULL REFERENCES "usuario"("id_usuario")
    );
`
        .then(() => {
            sql`

                CREATE TABLE "ingredients" (
                "id_ingredient" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "name" varchar(255) UNIQUE NOT NULL
                );
            `
            .then(() => {
                sql`
                    CREATE TABLE "recipe_ingredients" (
                    "id_recipe" integer NOT NULL REFERENCES "recipes"("id_recipe"),
                    "id_ingredient" integer NOT NULL REFERENCES "ingredients"("id_ingredient"),
                    "quantity" varchar(50) NOT NULL
                    );
                `
                .then(() => {
                    console.log('Tabela criada')
                })
            })
        })
    })
})