GET http://localhost:3333/usuarios

###

POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "firstName": "silva", 
    "lastName": "melo", 
    "email": "ma2@email.com", 
    "password": "123"
}

###

POST http://localhost:3333/usuarios/login
Content-Type: application/json

{
    "email": "ma1@email.com", 
    "password": "123"
}

###

POST http://localhost:3333/recipes/search


###

POST http://localhost:3333/recipes/search
Content-Type: application/json

{
    "ingredients": [
        "aveia"
    ]
}

###

POST http://localhost:3333/recipes
Content-Type: application/json

{
    "title": "Mingau de Aveia Proteico 3", 
    "image": "https://guiadacozinha.com.br/wp-content/uploads/2023/02/mingau-de-aveia-proteico-768x619.jpg", 
    "description": "Delicioso mingau de aveia proteico...", 
    "ingredients": [
        {
            "nome": "aveia",
            "unidade_de_medida": "Xícara",
            "qtd": 1
        },
        {
            "nome": "leite",
            "unidade_de_medida": "Xícara",
            "qtd": 2
        },
        {
            "nome": "salada",
            "unidade_de_medida": "Colher de sopa",
            "qtd": 1
        }
    ], 
    "steps": "Misture todos os ingredientes em uma panela... - Cozinhe em fogo médio até engrossar...", 
    "calories": "250", 
    "prepTime": "10"
}

###

POST http://localhost:3333/recipes/12

###

GET http://localhost:3333/ingredients

###

POST http://localhost:3333/ingredients/mel

###

POST http://localhost:3333/ingredients/add/Amendoim